import Head from 'next/head'
import NavBar from '../components/nav-bar'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<>
			<Head>
				<title>benbaldwin.dev</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<section className={styles.heroSection}>
				<NavBar />
			</section>
		</>
	)
}
